// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using scms.Infrastructure.Persistence;

#nullable disable

namespace scms.Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260915140615_MasterHelperValueSeed")]
    partial class MasterHelperValueSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("SpecializationId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialization_id");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("SpecializationId")
                        .HasDatabaseName("ix_employees_specialization_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_employees_type_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.MasterValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_master_values");

                    b.ToTable("master_values", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5555555-0000-0000-0000-000000000001"),
                            Description = "Doctor",
                            DisplayName = "Doctor",
                            IsActive = true,
                            Key = "doctor",
                            Type = "EMPLOYEE_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0000-0000-0000-000000000002"),
                            Description = "Nurse",
                            DisplayName = "Nurse",
                            IsActive = true,
                            Key = "nurse",
                            Type = "EMPLOYEE_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0000-0000-0000-000000000003"),
                            Description = "Receptionist",
                            DisplayName = "Receptionist",
                            IsActive = true,
                            Key = "receptionist",
                            Type = "EMPLOYEE_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0000-0000-0000-000000000004"),
                            Description = "Administrator",
                            DisplayName = "Admin",
                            IsActive = true,
                            Key = "admin",
                            Type = "EMPLOYEE_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0000-0000-0000-000000000005"),
                            Description = "Other",
                            DisplayName = "Other",
                            IsActive = true,
                            Key = "other",
                            Type = "EMPLOYEE_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0002-0000-0000-000000000001"),
                            Description = "Walk In",
                            DisplayName = "Walk In",
                            IsActive = true,
                            Key = "walk_in",
                            Type = "VISIT_MODE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0002-0000-0000-000000000002"),
                            Description = "Scheduled",
                            DisplayName = "Scheduled",
                            IsActive = true,
                            Key = "scheduled",
                            Type = "VISIT_MODE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0003-0000-0000-000000000001"),
                            Description = "Male",
                            DisplayName = "Male",
                            IsActive = true,
                            Key = "male",
                            Type = "GENDER"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0003-0000-0000-000000000002"),
                            Description = "Female",
                            DisplayName = "Female",
                            IsActive = true,
                            Key = "female",
                            Type = "GENDER"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0003-0000-0000-000000000003"),
                            Description = "Other",
                            DisplayName = "Other",
                            IsActive = true,
                            Key = "other",
                            Type = "GENDER"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000001"),
                            Description = "A Positive",
                            DisplayName = "A+",
                            IsActive = true,
                            Key = "a_pos",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000002"),
                            Description = "A Negative",
                            DisplayName = "A-",
                            IsActive = true,
                            Key = "a_neg",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000003"),
                            Description = "B Positive",
                            DisplayName = "B+",
                            IsActive = true,
                            Key = "b_pos",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000004"),
                            Description = "B Negative",
                            DisplayName = "B-",
                            IsActive = true,
                            Key = "b_neg",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000005"),
                            Description = "O Positive",
                            DisplayName = "O+",
                            IsActive = true,
                            Key = "o_pos",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000006"),
                            Description = "O Negative",
                            DisplayName = "O-",
                            IsActive = true,
                            Key = "o_neg",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000007"),
                            Description = "AB Positive",
                            DisplayName = "AB+",
                            IsActive = true,
                            Key = "ab_pos",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0004-0000-0000-000000000008"),
                            Description = "AB Negative",
                            DisplayName = "AB-",
                            IsActive = true,
                            Key = "ab_neg",
                            Type = "BLOOD_GROUP"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0005-0000-0000-000000000001"),
                            Description = "Mr",
                            DisplayName = "Mr",
                            IsActive = true,
                            Key = "mr",
                            Type = "SALUTATION"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0005-0000-0000-000000000002"),
                            Description = "Mrs",
                            DisplayName = "Mrs",
                            IsActive = true,
                            Key = "mrs",
                            Type = "SALUTATION"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0005-0000-0000-000000000003"),
                            Description = "Ms",
                            DisplayName = "Ms",
                            IsActive = true,
                            Key = "ms",
                            Type = "SALUTATION"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0005-0000-0000-000000000004"),
                            Description = "Doctor",
                            DisplayName = "Dr",
                            IsActive = true,
                            Key = "dr",
                            Type = "SALUTATION"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0005-0000-0000-000000000005"),
                            Description = "Master",
                            DisplayName = "Master",
                            IsActive = true,
                            Key = "master",
                            Type = "SALUTATION"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0006-0000-0000-000000000001"),
                            Description = "Spouse",
                            DisplayName = "Spouse",
                            IsActive = true,
                            Key = "spouse",
                            Type = "RELATIONSHIP_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0006-0000-0000-000000000002"),
                            Description = "Parent",
                            DisplayName = "Parent",
                            IsActive = true,
                            Key = "parent",
                            Type = "RELATIONSHIP_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0006-0000-0000-000000000003"),
                            Description = "Sibling",
                            DisplayName = "Sibling",
                            IsActive = true,
                            Key = "sibling",
                            Type = "RELATIONSHIP_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0006-0000-0000-000000000004"),
                            Description = "Child",
                            DisplayName = "Child",
                            IsActive = true,
                            Key = "child",
                            Type = "RELATIONSHIP_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0006-0000-0000-000000000005"),
                            Description = "Friend",
                            DisplayName = "Friend",
                            IsActive = true,
                            Key = "friend",
                            Type = "RELATIONSHIP_TYPE"
                        },
                        new
                        {
                            Id = new Guid("e5555555-0006-0000-0000-000000000006"),
                            Description = "Other",
                            DisplayName = "Other",
                            IsActive = true,
                            Key = "other",
                            Type = "RELATIONSHIP_TYPE"
                        });
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permissions_role_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_specializations");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_specializations_department_id");

                    b.ToTable("specializations", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.TenantPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_employee_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Employee", b =>
                {
                    b.HasOne("scms.Domain.Entities.Tenant.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.HasOne("scms.Domain.Entities.Tenant.Specialization", "Specialization")
                        .WithMany("Employees")
                        .HasForeignKey("SpecializationId")
                        .HasConstraintName("fk_employees_specializations_specialization_id");

                    b.HasOne("scms.Domain.Entities.Tenant.MasterValues", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_master_values_type_id");

                    b.Navigation("Department");

                    b.Navigation("Specialization");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.RefreshToken", b =>
                {
                    b.HasOne("scms.Domain.Entities.Tenant.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.RolePermission", b =>
                {
                    b.HasOne("scms.Domain.Entities.Tenant.TenantPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("scms.Domain.Entities.Tenant.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Specialization", b =>
                {
                    b.HasOne("scms.Domain.Entities.Tenant.Department", "Department")
                        .WithMany("Specializations")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_specializations_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.User", b =>
                {
                    b.HasOne("scms.Domain.Entities.Tenant.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("scms.Domain.Entities.Tenant.User", "EmployeeId")
                        .HasConstraintName("fk_users_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.UserRole", b =>
                {
                    b.HasOne("scms.Domain.Entities.Tenant.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("scms.Domain.Entities.Tenant.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Employee", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.Specialization", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.TenantPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("scms.Domain.Entities.Tenant.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
